### ISSUE TITLE
can't get it to work...

### ISSUE THREAD

**Issue by dennisvanderhave** [rfxcom/node-rfxcom#32]
Hi there,

I'm trying to make a web-app with node.js express.js and els. But if got some startup problems.

Downloaded your node-module. and programed everything in my routes:index.js
Then i programmed it to my index.ejs and make a button with rout to my index.js.

When i start up my web-app. Ten vfxcom blinks with the green light 2 time's and give me a message.

but the button will do nothing.

I hope you can help me. I could send you my files that you can take a look at it.

thanks in advance,

greets,

Dennis

**Comment by bigkevmcd** [comment]
Hey Dennis,

What is the message you receive?

Have you seen https://github.com/bigkevmcd/node-rfxcom/wiki/Simple-restify-example ?

Kevin

**Comment by maxwellhadley** [comment]
This issue looks to have died...
