### ISSUE TITLE
RFY protocol

### ISSUE THREAD

**Issue by npenin** [rfxcom/node-rfxcom#34]
Hi,

Does your project handle Somfy RTS protocol (referenced as RFY in RFXmgr). If so, how should it be used. If not, any chance to see it implemented ? I could also implement it by myself, but I have no clue to know the frames sent on the serial port.

Thanks,
Nicolas

**Comment by gizimoto** [comment]
I have created a fork with RFY protocol implementation and submitted a pull request.  Be great to have a second person test the implementation.

**Comment by cedbale** [comment]
@gizimoto I have tested it on my side and this run pretty well !

**Comment by maxwellhadley** [comment]
Recent changes to the package (0.10.1 and above) mean the original PR no longer merges without conflicts, and the packets received from the RFX have also been changed (firmware 1000 and greater). @gizmoto is looking at a revised PR now

**Comment by Averelll** [comment]
I tested gizmoto's code, works for me.

**Comment by maxwellhadley** [comment]
RFY support now added, based on @gizimoto's code
