### ISSUE TITLE
rfxcom works with node.js x64 0.12.0 but not with 0.12.2

### ISSUE THREAD

**Issue by nattlip** [rfxcom/node-rfxcom#35]

**Comment by maxwellhadley** [comment]
Rfxcom is now working on node.js version 0.12.13 - do you still have a problem or can we close this issue?

**Comment by nattlip** [comment]
i have to try

**Comment by maxwellhadley** [comment]
From version 1.0.0 onwards, node-rfxcom requires node version >= 4.8, so I'm closing this issue
