### ISSUE TITLE
Im looking for the way to sent info to a "click on click off" device

### ISSUE THREAD

**Issue by k-mooijman** [rfxcom/node-rfxcom#57]
Hi i managed to receive all the commands send by my emitters ( remotes and door sensors)
But i could not find a way to send a command to a device 
Can you please help me

**Comment by maxwellhadley** [comment]
Hi,

I think the missing piece of information may be that KlikAanKlikUit devices use the 'AC' protocol. I don't have any of these devices here to check, but it should all be working OK.

The data in the received event from the remote control will include a property called `subtype`. This is the index number into the array of subtype names in `lib/index.js`. For a `lighting2` packet this is:

    // Packet type 0x11
    exports.lighting2 = reflect(['AC', 'HOMEEASY_EU', 'ANSLUT', 'KAMBROOK']);
    exports.lighting2.transmitter = exports.Lighting2;
    Object.freeze(exports.lighting2);

(Ignore the `reflect()` function call for now). You should be getting a subtype of 0, which is the first entry - `AC`. You then need to create a `lighting2` transmitter using this subtype:

    var rfxtrx = new rfxcom.RfxCom("/dev/ttyUSB0", {debug: true}),
    lighting2 = new rfxcom.Lighting2(rfxtrx, rfxcom.lighting2.AC);

Then you can send commands using this transmitter. You need to determine the actual `id` & `unitcode` from the properties of the received event from the controller, and pass them to the appropriate transmitter function. These expect either an array of strings, or a single string with a '/' delimiting the two. Assuming your received event data is in `evt`, you do either

    var IdAsArray = [evt.id, evt.unitcode.toString(16)],
        IdAsString = evt.id + "/" + evt.unitcode.toString(16);

Note the unitcode must always be given as a hexadecimal string. Then you call the appropriate method of the transmitter:

    lighting2.switchOn(IdAsArray);    // Aan
    lighting2.switchOff(IdAsString);  // Uit

Hopefully this will get you going!

**Comment by k-mooijman** [comment]
Thanks a lot !! 
I managed to sent a command `lighting2.switchOn('0xA6C70A/1');` and it worked !
The receive message was `[rfxcom] on /dev/ttyUSB0 - Received: 0B,11,00,03,00,A6,C7,0A,01,00,00,80`
I already found out that AC uses 0B,11 ass the protocol indicator 
The A6,C7,0A should be the board code with the folowing 01 as the swich code 
Annyhou I'm very glad it works , when i have more time i'll investigate further on how to implement it in my project

**Comment by maxwellhadley** [comment]
Hang on - you seem to be just using the console output to receive the commands from the KAKU remote. You should install a handler on the "lighting2" event of the rfxcom object, which will be called any time a remote message is received:

    var rfxtrx = new rfxcom.RfxCom("/dev/ttyUSB0", {debug: true});

    /*
    * This reports lighting2 command messages
    */
    rfxtrx.on("lighting2", function (evt) {
            console.log("Subtype %d message received", evt.subtype, evt.id);
            console.log("ID: '%s/%s'", evt.id, evt.unitcode.toString(16));
            console.log("Command number %d - %s", evt.commandNumber, evt.command);
        });

(Or something like that)
