### ISSUE TITLE
Handler for HIDEKI sensor

### ISSUE THREAD

**Issue by m6246** [rfxcom/node-rfxcom#59]
I recently bought the Cresta TX-320 temperature/hydro sensor which uses the HIDEKI protocol. However, there does not seem to be a handler for this?

Sample raw bytes from the receive event:
[ 10, 82, 7, 12, 42, 14, 0, 217, 51, 1, 105 ]

**Comment by maxwellhadley** [comment]
This protocol doesn't seem to be supported by the RFXtrx433 (at least not yet) so I am unable to add it to this package. I suggest you contact RFXCOM directly and ask if it can be added:

[https://shop.strato.com/epages/78165469.sf/en_GB/?ObjectPath=/Shops/78165469/Categories/ContactForm](url)

**Comment by m6246** [comment]
Sorry, I forgot to mention I´m using a RFXtrx433e but I guess that version is not being targetted by this library then.

**Comment by m6246** [comment]
I actually got this working by listening for the ´th7´ event. Based on the raw data given in my first post, the second value 82/0x52 would map to 'temphumidity19Handler' which in turn emits to 'th' + the third data value.

Thanks for this great lib!

**Comment by maxwellhadley** [comment]
You are quite correct! The only reference to 'HIDEKI' protocol in the RFXCOM SDK documentation is in the 'undecoded packet' message, so I assumed it wasn't supported. The actual sensor type is referred to as just 'Cresta', and it gives, as you found, a 'th7' event - the sensor subtype in node-rfxcom is called 'TH7'.

For historical reasons, all the 'sensor' type packets emit different events for each subtype, whereas most other packet types use the same event for for all subtypes. This struck me as being wrong, somehow, but I couldn't justify changing it and breaking peoples' code. However, your issue would never have arisen if there was just a single 'th' event to listen too. I will probably implement packet-specific events for 'sensor' packets in a future release, initially in addition to the subtype-specific event, which I will deprecate, and then kill off some time later.
