### ISSUE TITLE
Version 1.0.0 release - advanced warning

### ISSUE THREAD

**Issue by maxwellhadley** [rfxcom/node-rfxcom#61]
I am in the process of preparing a new release, which will break backward compatibility and therefore warrants a major version number change. Significant differences are:

- Drop support for NodeJS versions <4.0.0
- Change API for the Curtain1 transmitter to bring it into line with all the others
- Change the semantics of some of the Lighting5 transmitter API to accommodate the many new subtypes added in recent RFX firmware, and the new commands added to support them
- Drop the options parameter to Lighting5 switchOn(), which currently allows dim level or mood values to be supplied. Use the setLevel() and setMood() commands instead

This release is being developed against the latest RFXCOM firmware version, currently 1020. Please make any complaints, comments, or suggestions here.

**Comment by basvdijk** [comment]
Great! Any thoughts about a release date yet?

**Comment by maxwellhadley** [comment]
@basvdijk How about September 7th? ;)
