### ISSUE TITLE
Chime event names not in sync

### ISSUE THREAD

**Issue by basvdijk** [rfxcom/node-rfxcom#65]
When I want to trigger a chime I send a `chime` event. However when I use the hardware-button of my chime it receives an `on` event instead of a `chime`.

My recommendation would be to use `chime` for both situations so the naming of these events are in sync with each other.

**Comment by maxwellhadley** [comment]
I'm a bit confused here: to transmit a chime command, you need to call the chime() function of a Transmitter object - either Chime1.chime() or Lighting1.chime() depending on which type of doorbell you have. When you receive a message from the bell push, you will get an event which is either "chime1" or "lighting1", again depending on the type of doorbell. There is no such thing as an "on" event.

What type of doorbell do you have, and what packet type & subtype do you use?

**Comment by basvdijk** [comment]
I am sorry, I made a mistake in my home automation code where `chime` was replaced with `on`
