### ISSUE TITLE
Reopen issue #44

### ISSUE THREAD

**Issue by stephjj** [rfxcom/node-rfxcom#69]
On a 5 button remote, the max unit number is 8.
And is the first button.

See https://github.com/rfxcom/node-rfxcom/issues/44

**Comment by maxwellhadley** [comment]
It looks like the RFXCOM SDK didn't get updated, and I changed back to 5 when I did a big catch-up with recent versions of the firmware. What firmware version are you using?

I have raised this issue with RFXCOM support:

> Bert,
A user of my node-rfxcom library has just re-opened an issue:
https://github.com/rfxcom/node-rfxcom/issues/44
This relates to the highest unit code number allowed in a Blyss lighting6 command. It looks like this is actually 8, not 5. Firmware type 1 1022 enforces 5 as the maximum allowed unit code, as does RFXmngr 18.0.0.18. The SDK version 9.15 also has 5.
Looking at my VCS history, I see I changed the limit in my package to 8 on 2016-04-13, but then reverted to 5 again on 2017-06-30, when I did a big update to catch up with recent firmware changes - this is presumably what provoked https://github.com/stephjj to re-open the issue.
Was there ever a firmware version that allowed unit codes up to 8? It looks like 8 may be the correct value.
Please can you copy the re-opened issue https://github.com/rfxcom/node-rfxcom/issues/69 with any updates,
Many thanks,
Max

**Comment by maxwellhadley** [comment]
Bert has replied that the maximum unit code should still be 5, but it may _possibly_ have been incorrectly displayed as 8 in an old version of RFXmngr. Which version of RFXmngr are you using, and which firmware? The latest revisions are RFXmngr 18.0.0.18 and firmware 1022.

It's odd you don't see a unit code 6 or 7

**Comment by stephjj** [comment]
Hello Max,
I dont use a RFXCom :-)I decode directly the radio protocol (with an Arduino) and I send the command to my Raspberry with the RFXCom protocol.
The Channel (in Blyss protocol) is mapped to the Unit Code in RFXCom. The Channel is 4 bits.On my 5 buttons remote, I have this mapping : CH_1= 8, CH_2 = 4, CH_3 = 2, CH_4 = 1, CH_5 = 3, CH_ALL = 0
The Global Channel (in Blyss) is also 4 bits. It is mapped to the Group Unit in RFXCom
And the mapping is :CH_A= 0, CH_B = 1, CH_C = 2, CH_D = 3, CH_E = 4

So, if the RFXCom SDK said that the max number is five, the real protocol doesn't agree ;-)
Thanks,Stéphane.
 

    Le Lundi 20 novembre 2017 12h03, Max Hadley <notifications@github.com> a écrit :
 

 Bert has replied that the maximum unit code should still be 5, but it may possibly have been incorrectly displayed as 8 in an old version of RFXmngr. Which version of RFXmngr are you using, and which firmware? The latest revisions are RFXmngr 18.0.0.18 and firmware 1022.It's odd you don't see a unit code 6 or 7—

**Comment by maxwellhadley** [comment]
The RFXCOM communication protocol is licensed for use with RFXCOM products only, and this issue does not arise when so so used. I can't/won't support use of the node-rfxcom package in contravention of the licensing terms.

I am closing this issue

**Comment by stephjj** [comment]
Okay but I dont use a RFXCOM, only your code.You can write whatever you want in your code.
Or I miss something and in fact you works for RFXcom and the license for node-rfxcom is misleading.
Anyway, it was only to help you to write a code which works in all case. Even for equipement that RFXcom doesn't even know it exists.
 

    Le Mardi 21 novembre 2017 18h06, Max Hadley <notifications@github.com> a écrit :
 

 The RFXCOM communication protocol is licensed for use with RFXCOM products only, and this issue does not arise when so so used. I can't/won't support use of the node-rfxcom package in contravention of the licensing terms.I am closing this issue—

**Comment by maxwellhadley** [comment]
I do not work for RFXCOM or have any commercial connection with them, other than as a customer. The code in this project is licensed under the MIT license, and like anybody else, you are free to do whatever you want with it under the terms of that license.

The SDK documentation supplied to me by RFXCOM, and which is used to design, implement, & test the code in this package, is copyright RFXCOM and issued under an agreement that it is used only in conjunction with RFXCOM products. Consequently I will not use it to provide support for non-rfxcom devices.
