### ISSUE TITLE
Getting EV1527 protocol info

### ISSUE THREAD

**Issue by k-mooijman** [rfxcom/node-rfxcom#76]
Hi 
What is the correct way to get  EV1527 protocol info ? 
It comes true as lighting4 but without useful data or info
Thanks 
    Kasper

**Comment by maxwellhadley** [comment]
Lighting4 is an odd one: basically, it is the 'native' protocol of the PT2262, EV1527, and similar chips used by very many cheap RF sensors and switches. These basically transmit a just 24-bit binary number. The allocation of meaning to these bits - i.e. which bits are 'address' and which 'data', is up to the circuit designer and there is no standard (although some of the transmitter chips implement use 12 of the bits as an address).

You will have to reverse-engineer how the bits are being used, I'm afraid, by exercising the device/sensor and noting the data values received.

**Comment by k-mooijman** [comment]
do you have any documentation ( useful ) on this protocol ? 
I would like to try to reverse-engineer this but anny info to get started is welcome !

**Comment by maxwellhadley** [comment]
I don't have any specific documentation. Try googling 'EV1527 protocol' - it brought up some useful-looking pages for me

**Comment by maxwellhadley** [comment]
Closing stale (non) issue
