### ISSUE TITLE
New firmware types Pro 1/2 are not recognized and show as undefined

### ISSUE THREAD

**Issue by emes** [rfxcom/node-rfxcom#78]

**Comment by maxwellhadley** [comment]
This has been on my to-do list for a while now. There are other changes, to support new devices, that will need to be made as well, as soon as I get the time :)

**Comment by maxwellhadley** [comment]
Basic support added from #79 - full support remains to be done

**Comment by maxwellhadley** [comment]
Full support now added in #80 and published to npm as version 2.0.0. This doesn't support the ASYNC port on the ProXL hardware, as I haven't got one to test with! (any offers?)
