### ISSUE TITLE
running in the JVM ?!?

### ISSUE THREAD

**Issue by k-mooijman** [rfxcom/node-rfxcom#83]
Hi 
By a lack of a ( findable ) java driver/sdk for the rfxcom i would like to use the javascript in the jvm ( nashorn ) do you have any experience with this ? can you tell me how to use your libraries without NPM ?

**Comment by maxwellhadley** [comment]
It is possible to simply clone this repository from Github, without using `npm`, but you will then have to locate and install the dependencies yourself, from their Github repositories. One of the packages that `node-rfxcom` depends on is `serialport`, parts of which are written in C++ and link against the NodeJS platform native interface libraries. I have no experience with `nashorn` but I doubt if it will support this. I think you would have to replace it with a Java equivalent, if one exists, to access the FTDI serial device.

However, I know that at least one of the Domotics applications that use RFXCOM is written in Java, so there must be some Java software somewhere that does the job. Have you tried asking RFXCOM if they know of any?

**Comment by k-mooijman** [comment]
Thanks for your response I'll have a look at the Domotics applications !

**Comment by maxwellhadley** [comment]
Closing this stale issue
