### ISSUE TITLE
Somfy example won't work because of renamed (?) command

### ISSUE THREAD

**Issue by emeidi** [rfxcom/node-rfxcom#87]
Instead of

`rfy.do(["0x10203", "1"], "down");`

in `README.md` it should read

`rfy.doCommand(["0x10203", "1"], "down");`

as rfy.do() is (not anymore?) mentioned in `/lib/rfy.js`

**Comment by maxwellhadley** [comment]
Well spotted! I will fix this in the next version

**Comment by maxwellhadley** [comment]
Fixed in #90 (version 2.1.0)
